[package]
name = "IMOMD-RRTStar"
version = "0.1.0"
edition = "2021"
description = "Informable Multi-Objective and Multi-Directional RRT* System for Path Planning.This work reimplemented an anytime iterative system to concurrently solve the multi-objective path planning problem and determine the visiting order of destinations using rust-lang.related paper:https://arxiv.org/abs/2205.14853"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "IMOMD_RRTStar"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "main"
path = "src/main.rs"

[dependencies]
clap = { version = "4.3.19", features = ["derive"] }
env_logger = "0.10.0"
log = "0.4.19"
polars-core = {version="0.31.1",features=["fmt"]}
pyo3 = { version = "0.18.1", features = ["extension-module"] }
serde = { version = "1.0.180", features = ["derive"] }
serde_yaml = "0.9.25"


[package.metadata.maturin]
python-source = "python"
