general:
  system: 0
  pseudo: 0
  log_data: 0
  print_path: 0
  max_iter: 1000000
  max_time: 60

rrt_params:
  goal_bias: 1.0
  random_seed: 0

destinations:
  source_id: 0
  objective_ids: [1]
  target_id: 2

map:
  type: 0
  path: tests/fixtures/
  name: custom_graph.yaml

rtsp_settings:
  shortcut: 1
  swapping: 1
  genetic: 1
  ga:
    random_seed: 0
    mutation_iter: 10000
    population: 1000
    generation: 5
